name: Docker production build

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup
        run: | 
          cp env.sample .env
          cp docker/tess.docker-test.yml config/tess.yml
          cp config/secrets.example.yml config/secrets.yml
      - name: Build & run
        run: docker compose -f docker-compose-prod.yml up --build --detach --wait --wait-timeout 60
      - name: Docker ps
        run: sleep 120 | docker ps -a
      - name: Setup
        run: docker compose -f docker-compose-prod.yml exec app bundle exec rake db:setup DISABLE_DATABASE_ENVIRONMENT_CHECK=1
      - name: Test
        run: docker compose logs -f app & curl -v http://localhost:3000/ | sleep 6
